# версия синтаксиса
version: '3'

# в этом блоке мы описываем контейнеры, которые будут запускаться
services:
  #Контейнер с PHP, назовём его app
  app_b1:
    # Если нет секции build, то система будет искать образ в репозиториях
    build:
      context: .
      dockerfile: fpm/Dockerfile
    image: myapp/php # имя будущего образа
    container_name: app_b1 # имя контейнера после запуска
    volumes:
      - ../code:/data/app
    # мы можем создать для контейнеров внутреннюю сеть
    networks:
      - app-network_b1

  #контейне с Nginx
  webserver_b1:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: myapp/nginx
    container_name: webserver_b1
    # проброс портов
    ports:
      - "80:80"
    volumes:
      - ../code:/data/app
    networks:
      - app-network_b1

#Docker Networks
networks:
  app-network_b1:
    driver: bridge